slam_toolbox:
  ros__parameters:
    # use_sim_time: true

    # ROS Parameters
    # odom_frame: odom_kinematics
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    scan_queue_size: 5000
    
    do_loop_closing: true
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 1.0
    transform_publish_period: 0.05
    # map_update_interval: 1.0
    map_update_interval: 0.1
    publish_frame_period: 0.05
    laser_min_range: 0.5
    laser_max_range: 10.0
    minimum_time_interval: 0.25
    maximum_laser_scan_time: 1.0
    use_scan_matching: true
    minimum_travel_distance: 0.2
    loop_match_minimum_chain_size: 8
    # loop_match maximum_variance_coarse: 0.3
    # loop_match minimum_response_coarse: 0.6
    # loop_match minimum_response_fine: 0.78