slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    scan_queue_size: 5000
    
    resolution: 0.05
    max_laser_range: 30.0
    minimum_time_interval: 1.0
    transform_publish_period: 0.05
    map_update_interval: 5.0
    publish_frame_period: 0.05
    laser_min_range: 0.5
    laser_max_range: 10.0
    minimum_time_interval: 0.25
    maximum_laser_scan_time: 1.0
    map_update_interval: 0.5
    use_scan_matching: true