ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    transform_time_offset: 0.0
    transform_timeout: 0.0
    print_diagnostics: true

    odom0: /odom
    odom0_config: [true,  true,  true,  # x, y, z positions
                  true,  true,  true, # roll, pitch, yaw orientations (from IMU)
                  true,  true,  true,  # x, y, z linear velocities
                  true,  true,  true, # roll, pitch, yaw angular velocities (from IMU)
                  false, false, false,] # x, y, z linear accelerations

    imu0: /imu
    imu0_config: [false, false, false, # x, y, z positions (from odom)
                  true,  true,  true,  # roll, pitch, yaw orientations
                  false, false, false, # x, y, z linear velocities (from odom)
                  true,  true,  true,  # roll, pitch, yaw angular velocities
                  true,  true,  true,] # x, y, z linear accelerations (use velocities from odom)

    imu0_differential: false
    imu0_remove_gravitational_acceleration: true

    # use_control: false

    # stamped_control: false
    # control_timeout: 0.2
    # control_config: [true, true, false,
    #                 false, false, false]

    # accel_noise: 0.2
    # accel_bias_noise: 0.0002
    # accel_bias_init: [0.0, 0.0, 0.0]
    # accel_bias_variance: 1.0e-6

    # gyro_noise: 0.01
    # gyro_bias_noise: 0.00002
    # gyro_bias_init: [0.0, 0.0, 0.0]
    # gyro_bias_variance: 1.0e-6
    # initial_estimate_covariance: [1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6,  1.0e-6,  1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6, 1.0e-6]
    # process_noise_covariance: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,  1.0,  1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

    # initial_estimate_covariance: [1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0,
    #                               0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6]

    # process_noise_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.2, 0.0, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.2, 0.0, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.2, 0.0,
    #                           0.0, 0.0, 0.0, 0.0, 0.0, 0.2]

    # initial_estimate_covariance: [
    #   1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # x
    #   0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # y
    #   0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # z
    #   0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # roll
    #   0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # pitch
    #   0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # yaw
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_z
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, 0.0, # ang_vel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, 0.0, # ang_vel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, 0.0, # ang_vel_z
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, 0.0, # accel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6, 0.0, # accel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0e-6  # accel_z
    # ]

    # process_noise_covariance: [
    #   1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # x
    #   0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # y
    #   0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # z
    #   0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # roll
    #   0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # pitch
    #   0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # yaw
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, # vel_z
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, # ang_vel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, # ang_vel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, # ang_vel_z
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, # accel_x
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, # accel_y
    #   0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0  # accel_z
    # ]




    debug: true
    publish_tf: true
    publish_acceleration: false

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
