controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - fr_j0
        - fr_j1
        - fl_j0
        - fl_j1
        - rl_j0
        - rl_j1
        - rr_j0
        - rr_j1

      state_publish_rate: 25
      command_interfaces: 
        - position
      state_interfaces:
        - position
