slam_toolbox:
  ros__parameters:
    # Modified slam toolbox with velocity constraints parameters
    # use_velocity_constraints: true

    # ROS Parameters
    # odom_frame: odom_kinematics
    odom_frame: odom
    map_frame: map
    # base_frame: base_link
    scan_topic: /scan
    scan_queue_size: 500
    
    do_loop_closing: true
    resolution: 0.05
    max_laser_range: 20.0
    min_laser_range: 0.0

    # transform_timeout: 0.2
    # tf_buffer_duration: 1.0
    # scan_buffer_maximum_scan_distance # TODO: Add this parameter

    # minimum_time_interval: 0.25
    # minimum_time_interval: 1.0
    # transform_publish_period: 0.1
    transform_publish_period: 0.05
    # map_update_interval: 1.0
    # map_update_interval: 0.5
    map_update_interval: 0.01
    # publish_frame_period: 0.1
    # publish_frame_period: 0.05
    # minimum_time_interval: 1.5
    minimum_time_interval: 0.1
    use_scan_matching: true
    # minimum_travel_distance: 0.5
    # minimum_travel_distance: 0.3
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.008

    # loop_match_minimum_chain_size: 8q
    loop_match_minimum_chain_size: 7
    
    # loop_match_minimum_chain_size: 10
    # loop_match maximum_variance_coarse: 0.3
    # loop_match minimum_response_coarse: 0.6
    # loop_match minimum_response_fine: 0.78